#!/usr/bin/env python3
"""Fine-tune the primary medical evidence retriever with TripletLoss.

This script trains a BAAI/bge-m3 model to better retrieve medical evidence for claim verification.

PIPELINE OVERVIEW:
1. Loads LLM-labeled claims from retriever/data/labeled/claims_llm_labeled.json
   (generated by retriever/notebooks/colab_gemma_claim_labeler.ipynb)
2. Builds (anchor, positive, negative) triplets from claim + evidence pairs
3. Trains with sentence-transformers TripletLoss using cosine similarity
4. Saves fine-tuned model to storage/models/fine_tuned_medical_retriever/

USAGE:
    # From misinformation_research/ directory
    python -m retriever.train_triplet_retriever

    # With custom config (e.g., more epochs)
    from retriever.config import TrainingConfig
    from retriever.train_triplet_retriever import main
    main(TrainingConfig(epochs=4, batch_size=32))

REQUIREMENTS:
- Qdrant collection 'medical_facts_global' populated (run build_qdrant_incremental.py first)
- Labeled claims file with positive_evidence/negative_evidence arrays
- GPU recommended (2-4 GB VRAM for batch_size=16)

OUTPUTS:
- Fine-tuned model: storage/models/fine_tuned_medical_retriever/
- Triplet audit: retriever/data/training/retrieval_triplets.jsonl
- Training logs: stdout (loss, eval metrics per epoch)

CONFIGURATION:
All hyperparameters in retriever/config.py TrainingConfig dataclass.
Override via environment variables or pass TrainingConfig to main().
"""

from __future__ import annotations

import json
import math
import random
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, List, MutableMapping, Sequence

import torch
from sentence_transformers import InputExample, SentenceTransformer, losses
from sentence_transformers.evaluation import TripletEvaluator
from sentence_transformers.util import batch_to_device
from torch.utils.data import DataLoader
from tqdm.auto import tqdm

from .config import (
    TrainingConfig,
    DATA_LABELED_DIR,
    DEFAULT_TRAINING,
    CLAIM_TEXT_KEYS,
)


@dataclass(frozen=True)
class TripletRow:
    claim_id: str
    anchor: str
    positive: str
    negative: str


@dataclass(frozen=True)
class TripletBuildResult:
    triplets: List[TripletRow]
    skipped_claims: int


def normalize_space(text: str) -> str:
    return " ".join(str(text or "").split()).strip()


def load_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def claim_records(data: Any) -> List[MutableMapping[str, Any]]:
    if isinstance(data, list):
        records = data
    elif isinstance(data, dict) and isinstance(data.get("claims"), list):
        records = data["claims"]
    else:
        raise ValueError("Input JSON must be a list or an object with a 'claims' list.")

    out: List[MutableMapping[str, Any]] = []
    for index, record in enumerate(records):
        if not isinstance(record, dict):
            raise ValueError(f"Claim record at index {index} is not an object.")
        out.append(record)
    return out


def claim_text(record: MutableMapping[str, Any]) -> str:
    for key in CLAIM_TEXT_KEYS:
        value = record.get(key)
        if isinstance(value, str) and value.strip():
            return normalize_space(value)

    claim_id = record.get("id", "<missing id>")
    raise ValueError(f"Claim {claim_id} has no claim text. Expected one of {CLAIM_TEXT_KEYS}.")


def evidence_text(evidence: Any) -> str:
    if isinstance(evidence, str):
        return normalize_space(evidence)

    if not isinstance(evidence, dict):
        return ""

    parts = [
        evidence.get("title") or "",
        evidence.get("section_heading") or "",
        evidence.get("text") or "",
    ]
    return normalize_space(" ".join(part for part in parts if part))


def unique_texts(items: Iterable[Any]) -> List[str]:
    texts: List[str] = []
    seen = set()
    for item in items:
        text = evidence_text(item)
        if not text or text in seen:
            continue
        seen.add(text)
        texts.append(text)
    return texts


def build_triplets(
    records: Sequence[MutableMapping[str, Any]],
    negatives_per_positive: int,
    rng: random.Random,
) -> TripletBuildResult:
    triplets: List[TripletRow] = []
    skipped_claims = 0

    for index, record in enumerate(records):
        positives = unique_texts(record.get("positive_evidence") or [])
        negatives = unique_texts(record.get("negative_evidence") or [])
        if not positives or not negatives:
            skipped_claims += 1
            continue

        anchor = claim_text(record)
        claim_id = normalize_space(record.get("id") or f"claim_{index + 1:04d}")

        for positive in positives:
            shuffled_negatives = list(negatives)
            rng.shuffle(shuffled_negatives)
            if negatives_per_positive > 0:
                shuffled_negatives = shuffled_negatives[:negatives_per_positive]

            for negative in shuffled_negatives:
                triplets.append(
                    TripletRow(
                        claim_id=claim_id,
                        anchor=anchor,
                        positive=positive,
                        negative=negative,
                    )
                )

    rng.shuffle(triplets)
    return TripletBuildResult(triplets=triplets, skipped_claims=skipped_claims)


def split_triplets(
    triplets: Sequence[TripletRow],
    eval_fraction: float,
    seed: int,
) -> tuple[List[TripletRow], List[TripletRow]]:
    shuffled = list(triplets)
    random.Random(seed).shuffle(shuffled)

    if eval_fraction <= 0 or len(shuffled) < 10:
        return shuffled, []

    eval_count = max(1, math.floor(len(shuffled) * eval_fraction))
    eval_count = min(eval_count, len(shuffled) - 1)
    return shuffled[eval_count:], shuffled[:eval_count]


def to_input_examples(rows: Sequence[TripletRow]) -> List[InputExample]:
    return [
        InputExample(texts=[row.anchor, row.positive, row.negative])
        for row in rows
    ]


def write_triplets_jsonl(path: Path, rows: Sequence[TripletRow]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        for row in rows:
            f.write(
                json.dumps(
                    {
                        "claim_id": row.claim_id,
                        "claim": row.anchor,
                        "positive_evidence": row.positive,
                        "negative_evidence": row.negative,
                    },
                    ensure_ascii=False,
                )
            )
            f.write("\n")


def linear_warmup_decay_lambda(current_step: int, *, warmup_steps: int, total_steps: int) -> float:
    if total_steps <= 0:
        return 1.0

    if warmup_steps > 0 and current_step < warmup_steps:
        return float(current_step) / float(max(1, warmup_steps))

    remaining_steps = total_steps - current_step
    decay_steps = max(1, total_steps - warmup_steps)
    return max(0.0, float(remaining_steps) / float(decay_steps))


def train_with_triplet_loss(
    *,
    model: SentenceTransformer,
    train_rows: Sequence[TripletRow],
    evaluator: TripletEvaluator | None,
    config: TrainingConfig,
) -> None:
    train_dataloader = DataLoader(
        to_input_examples(train_rows),
        shuffle=True,
        batch_size=config.batch_size,
        collate_fn=model.smart_batching_collate,
    )
    train_loss = losses.TripletLoss(model=model, triplet_margin=config.triplet_margin)

    total_steps = len(train_dataloader) * config.epochs
    warmup_steps = min(config.warmup_steps, max(0, total_steps - 1))
    optimizer = torch.optim.AdamW(
        train_loss.parameters(),
        lr=config.learning_rate,
        weight_decay=config.weight_decay,
    )
    scheduler = torch.optim.lr_scheduler.LambdaLR(
        optimizer,
        lr_lambda=lambda step: linear_warmup_decay_lambda(
            step,
            warmup_steps=warmup_steps,
            total_steps=total_steps,
        ),
    )

    print(f"[Train] Total optimization steps: {total_steps}")
    print(f"[Train] Warmup steps: {warmup_steps}")

    global_step = 0
    for epoch in range(config.epochs):
        train_loss.train()
        epoch_loss = 0.0

        progress = tqdm(
            train_dataloader,
            desc=f"Epoch {epoch + 1}/{config.epochs}",
            leave=True,
        )
        for sentence_features, labels in progress:
            sentence_features = [
                batch_to_device(sentence_feature, model.device)
                for sentence_feature in sentence_features
            ]
            labels = labels.to(model.device)

            optimizer.zero_grad(set_to_none=True)
            loss_value = train_loss(sentence_features, labels)
            loss_value.backward()
            torch.nn.utils.clip_grad_norm_(train_loss.parameters(), config.max_grad_norm)
            optimizer.step()
            scheduler.step()

            global_step += 1
            epoch_loss += float(loss_value.detach().cpu())
            progress.set_postfix(loss=f"{loss_value.item():.4f}")

        average_loss = epoch_loss / max(1, len(train_dataloader))
        print(f"[Train] Epoch {epoch + 1} average loss: {average_loss:.4f}")

        if evaluator is not None:
            metrics = evaluator(model, epoch=epoch, steps=global_step)
            formatted_metrics = ", ".join(
                f"{key}={value:.4f}" for key, value in sorted(metrics.items())
            )
            print(f"[Eval] {formatted_metrics}")


def main(config: TrainingConfig = DEFAULT_TRAINING) -> None:
    if config.batch_size < 1:
        raise ValueError("batch_size must be at least 1.")
    if config.negatives_per_positive < 0:
        raise ValueError("negatives_per_positive must be 0 or greater.")

    labeled_claims_file = DATA_LABELED_DIR / "claims_llm_labeled.json"

    data = load_json(labeled_claims_file)
    records = claim_records(data)
    rng = random.Random(config.random_seed)
    build_result = build_triplets(records, config.negatives_per_positive, rng)
    triplets = build_result.triplets

    if not triplets:
        raise RuntimeError(
            "No triplets found. Each usable claim needs at least one positive_evidence "
            "and one negative_evidence item with text."
        )

    write_triplets_jsonl(config.triplets_audit_file, triplets)
    train_rows, eval_rows = split_triplets(triplets, config.eval_fraction, config.random_seed)

    print(f"[Data] Claims loaded: {len(records)}")
    print(f"[Data] Claims skipped without positive or negative evidence: {build_result.skipped_claims}")
    print(f"[Data] Triplets built: {len(triplets)}")
    print(f"[Data] Train triplets: {len(train_rows)}")
    print(f"[Data] Eval triplets: {len(eval_rows)}")
    print(f"[Data] Triplet audit file: {config.triplets_audit_file.resolve()}")

    print(f"[Model] Loading base model: {config.base_model}")
    model = SentenceTransformer(config.base_model)

    evaluator = None
    if eval_rows:
        evaluator = TripletEvaluator.from_input_examples(
            to_input_examples(eval_rows),
            name="medical-evidence-triplets",
        )

    config.output_model_dir.parent.mkdir(parents=True, exist_ok=True)
    print(f"[Train] Saving fine-tuned model to: {config.output_model_dir.resolve()}")
    train_with_triplet_loss(model=model, train_rows=train_rows, evaluator=evaluator, config=config)
    model.save(str(config.output_model_dir))
    print("[Done] Fine-tuning complete.")


if __name__ == "__main__":
    main()